<template>
    <div>
        <Breadcrumbs PageTitle="vendor terms and conditions"
        PageLink="/vendor-terms-and-conditions"
        backgroundImage="https://d-themes.com/wordpress/wolmart/elements/wp-content/uploads/sites/3/2021/05/banner-1.jpg" />

        <div class="page-template-content" style="direction: rtl">
            <div class="container">
                <div class="bravo-text ">
                    <p>&nbsp;</p>
                    <p class="MsoNormal" style="text-align:right;">&nbsp;</p>
                    <hr>
                    <p class="MsoNormal" style="text-align:right;"><span style="font-size:16pt;font-family:Arial, 'sans-serif';">( مقدم الخدمه )</span><span style="font-size:12pt;font-family:'Times New Roman', serif;">&nbsp;</span><span style="font-size:12pt;font-family:Arial, 'sans-serif';">شركة عرابيا للاستثمار والتسويق الاليكترونى الكائن مقرها 455 شارع الكورنيش طريق عرابيا امام فندق بيروت ومسجلة فى السجل التجارى تحت رقم ( 50468 ) بمكتب سجل تجارى استثمار الغردقة &nbsp;ويمثلها فى التوقيع على هذا العقد السيد | عماد سيد محمد على بصفته ممثل ومالك الشركة ويشار اليها فيما يلى بمقدم الخدمه او عرابيا او هوتيلز ايجبت</span><span style="font-size:14pt;font-family:Arial, 'sans-serif';">.</span></p>
                    <p class="MsoNormal" style="text-align:right;"><span style="font-size:16pt;font-family:Arial, 'sans-serif';">( الشريك )</span><span style="font-size:12pt;font-family:'Times New Roman', serif;">&nbsp;</span><span style="font-size:12pt;font-family:'Times New Roman', serif;">&nbsp;</span><span style="font-size:12pt;font-family:Arial, 'sans-serif';">مستخدم منصة هوتيلز ايجيبت والمتعارف عليه من خلال الايمل الرسمى للشركه والحسابى البنكى سواء كان المالك او من ينوب عنه.</span></p>
                    <p class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:Arial, 'sans-serif';">حيث ان الشركة الطرف الاول يدير شركة بمقره الكائن يصدر هذا العقد ويقوم بأدارة مشروع هوتيلز ايجبت والمعلن عن طريق التطبيق وهو يقوم بتسهيل عميلة الحجز العملاء ويمكن للطرف الثانى عرض منتجاته وذلك نظير النسبة المتفق عليها بين الطرفين ويلتزم الطرف الثانى (الشريك)بالقيام بعملية البيع وادخال الاصناف والعروض والتسهيل عليها وتتمثل هذة المنتجات فى صورة غرف فندقية وشليهات وفيلات وشقق سكنية فاخرة ورحلات بحرية او سفارى بمختلف انوعها ويترتب هذا على الترخيص القانونى للطرف الثانى.</span></p>
                    <p class="MsoNormal" style="text-align:right;"><span style="font-size:14pt;font-family:Arial, 'sans-serif';">وقد اتفقا و تعاقدا على الاتى :-</span></p>
                    <p class="MsoNormal" style="text-align:right;"><strong><span style="font-size:16pt;font-family:Arial, 'sans-serif';">البند الأول :&nbsp;</span></strong><span style="font-size:12pt;font-family:Arial, 'sans-serif';">يعتبر هذا العقد رسمي ومعتد للعمل به بموجب قوانين و دستور جمهورية مصر العربية و بالاشتراك علي المنصة الاليكترونية بمثابة موافقتكم علي شروط التعاقد لتقديم الخدمة و التمهيد السابق جزء لا يتجزأ من هذا العقد.</span></p>
                    <p class="MsoNormal" style="text-align:right;"><strong><span style="font-size:16pt;font-family:Arial, 'sans-serif';">البند</span></strong><strong><span style="font-size:14pt;font-family:Arial, 'sans-serif';">&nbsp;الثانى – الخدمات :</span></strong></p>
                    <p class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:Arial, 'sans-serif';">اتفق الطرفان على ان يقوم الطرف الاول (مقدم الخدمه ) بالتسويق والدعايه اللازمه للتطبيق وصفحته بمنصات التواصل الاجتماعى بما يساعد على انتشار وتسويق التطبيق وجلب مبيعات للطرف الثانى (الشريك)<strong>.</strong></span></p>
                    <p class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:Arial, 'sans-serif';">يلتزم الطرف الاول بتوفير البوابات الالكترونيه عن طريق البطاقات البنكيه والمحافظ الإلكترونيه لعملائهم بناءا على حق الطرف الاول فى تمرير العمليات الإلكترونيه وإجراء التسويات والمقاصه على الحساب البنكى الخاص بالطرف الثانى.</span></p>
                    <ul>
                        <li class="MsoNormal" style="text-align:right;"><strong><span style="font-size:12pt;font-family:Arial, 'sans-serif';">البطاقات البنكيه</span></strong><span style="font-size:12pt;font-family:Arial, 'sans-serif';">&nbsp;: كافة انواع البطاقات المصدرة من طرف البنوك بإختلاف انواعها بطاقات دائنه ومسبوقة الدفع (&nbsp;</span><span style="font-size:12pt;font-family:'Times New Roman', serif;">credit prepaid debit</span><span style="font-size:12pt;font-family:Arial, 'sans-serif';">&nbsp;) و التى تحمل علامه إحدى المؤسسات العالميه (</span><span style="font-size:12pt;font-family:'Times New Roman', serif;">Master card , visa&nbsp;</span><span style="font-size:12pt;font-family:Arial, 'sans-serif';">&nbsp;) او تحمل علامه الشبكه الوطنيه (&nbsp;</span><span style="font-size:12pt;font-family:'Times New Roman', serif;">mezza</span><span style="font-size:12pt;font-family:Arial, 'sans-serif';">&nbsp;) ويمكن إستخدامها الكترونيا .</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:Arial, 'sans-serif';">&nbsp;<strong>المحافظ الإلكترونية</strong>&nbsp;: محافظ الهاتف المحمول الخاصه بالعملاء المشتركين بالخدمه لدى اى من البنوك او شركات المحمول المصرية والتى تمكنهم من الدفع الالكترونى باستخدام تقنية ال&nbsp;</span><span style="font-size:12pt;font-family:'Times New Roman', serif;">QR</span></li>
                        <li class="MsoNormal" style="text-align:right;"><strong><span style="font-size:12pt;font-family:Arial, 'sans-serif';">او ارسال طلب الدفع مباشرة على رقم الهاتف المحمول المسجل والمشترك بالخدمه.</span></strong></li>
                        <li class="MsoNormal" style="text-align:right;"><strong><span style="font-size:12pt;font-family:Arial, 'sans-serif';">الرقم المرجعى</span></strong><span style="font-size:12pt;font-family:Arial, 'sans-serif';">&nbsp;: الرقم المستخدم للسداد عن طريق اى من قنوات (فورى) والتى تتيح خدمات (&nbsp;</span><span style="font-size:12pt;font-family:'Times New Roman', serif;">fawry pay</span><span style="font-size:12pt;font-family:'Times New Roman', serif;">&nbsp;) ومنها على سبيل المثال وليس الحصر ( محلات التجزئة المنتشرة بجميع انحاء الجمهوريه القنوات البنكيه مثل ماكينات الالى (&nbsp;</span><span style="font-size:12pt;font-family:'Times New Roman', serif;">&nbsp;ATM</span><span style="font-size:12pt;font-family:Arial, 'sans-serif';">&nbsp;) وكذلك فروع ومنافذ فورى بلس وتطبيقات الهاتف (&nbsp;</span><span style="font-size:12pt;font-family:'Times New Roman', serif;">MY Fawry</span><span style="font-size:12pt;font-family:'Times New Roman', serif;">&nbsp;) وغيرها من القنوات التى يتم اضافتها من وقت اخر.</span></li>
                    </ul>
                    <p class="MsoNormal" style="text-align:right;"><strong><span style="font-size:14pt;font-family:Arial, 'sans-serif';">البند الثالث – الالتزامات :</span></strong></p>
                    <p class="MsoNormal" style="text-align:right;"><span style="font-size:14pt;font-family:Arial, 'sans-serif';">اولا: شركة هوتيلز ايجبت ( مقدم الخدمه )</span></p>
                    <ul>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:Arial, 'sans-serif';">توفير البيانات والمعلومات الخاصه بالعمليات الالكترونيه التى تتيح للشريك مراجعة كافة تفاصيل العمليات وغيرها من التقارير المتاحه وذلك من خلال لوحة التحكم المتاحه للشريك من قبل هوتيلز ايجبت وللشريك الحق فى تعريف اكثر من مستخدم للاطلاع على تلك البيانات وكذلك اعطائهم الصلاحيات المختلفه لإدارة الحساب</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:Arial, 'sans-serif';">تقديم خدمات الدعم الفنى للشريك فى حالة وجود اى اعطال ناتجه عن النظام او الخدمات الفرعيه المقدمه.</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:Arial, 'sans-serif';">توفير النظام والتاكد من استمرار الخدمه على مدار الساعه دون اى انقطاع ال فى حالة الظروف القهرية والتى تعنى ظروف طارئه غير متوقع سواء بالنظم او اسباب خارجه عن إرادة مقدم الخدمه ومنها على سبيل المثال وليس الحصر (الشغب – الاحتجاجات – الزلازل – القرارات العامه والاجراءات الحكوميه ) على ان يلتزم مقدم الخدمه باتخاذ كافة الاجراءات لاستعادة الخدمات بشكل طبيعى ومنتظم فى اقرب وقت.</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:Arial, 'sans-serif';">يلتزم الطرف الاول بتحويل صافى المبالغ المحصله بعد خصم العمولات المستحقه لحساب الشريك وذلك ثلاث مرات اسبوعيا على ان تكون تلك المتحصلات خاصه بالعمليات الناحجه المنفذه من خلال منصة مقدم الخدمه والمستوفاة لكافة البيانات المطلوبه لبيان صحتها عند الطلب.</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:Arial, 'sans-serif';">يلتزم الطرف الاول بمسئوليته الكامله عن تحويل المبالغ المحصله لحساب الطرف الثانى&nbsp; وفقا لشروط العقد دون أدنى مسئولبه قانونيه عليه فى استخدام المبالغ المحوله لحساب الطرف الثانى مقابل النحصيلات من خلال قنةاته الخاصه .</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:Arial, 'sans-serif';">يقر الطرف الثانى بصحه بيانات الحساب البنكى المذكوره فى عقد الخدمات الرئيسى واحقيته فى استلام مبالغ التحصيل على الحساب البنكى وكذلك بيانات الشخص المفوض والمسئول عن ادارة الحساب البنكى</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:'Times New Roman', serif;">يحق للطرف الاول تغير مقابل الخدمه (العموله) بعد اخطار الطرف الثانى والحصول على موافقته خلال مده اقصاها(14) يوم من تاريخ الطلب وتسرى العمولات الجديده على العمليات المنفذه بعد موافقة الطرف الثانى كتابيا او عن طريق البريد الالكترونى.</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:'Times New Roman', serif;">إتاحة او ارسال التقارير الماليه من أن لأخر عند الحاجه والتى توضح بيانات المعاملات المالية والتسوية ويلتزم الشريك بدفع الضرائب بالاضافه الى رسوم الخدمات المستحقه على ان يتحمل الشريك الضرائب المستحقة علية طبقا لمركزه القانونى ومنها ضريبة القيمة المضافة واى ضرائب اخرى سارية المفعول.</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:'Times New Roman', serif;">الحفاظ على سرية البيانات المتداولة بخصوص الخدمات المحددة والمذكورة فى هذا العقد.</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:'Times New Roman', serif;">يلتزم مقدم الخدمه بارسال كافة التقارير المتعلقة بالعمليات المشكوك فى مدى صحتها وسلامتها على البريد الالكترونى للشريك خلال خمسة ايام عمل من تاريخ اكتشافها او عند ورودها من المؤسسات الدوليه وذلك لاتخاذ الاجراءات اللازمة للحد منها.</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:'Times New Roman', serif;">المساعده والدعم الفنى فى تقديم الحملات الدعائيه وفقا لرؤيته التسويقية فى الاعلان والترويج عن الخدمات المقدمه وكذلك السماح للشريك باستخدام العلامة التجارية فى حملاتة الدعائيه بعد الموافقه على شكل ومحتوى الاعلان.</span></li>
                    </ul>
                    <p class="MsoNormal" style="text-align:right;"><span style="font-size:14pt;font-family:Arial, 'sans-serif';">ثانيا : ( الشريك</span> <span style="font-size:14pt;font-family:Arial, 'sans-serif';">)</span></p>
                    <ol>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:Arial, 'sans-serif';">يلتزم الطرف الثانى (الشريك)بمفرده عن الالتزام بالقوانين واللوائح والانظمه والمعاير المطبقه فى جمهرية مصر العربيه التى تتعلق بوزارة السياحه وامن وسلامة الزوار وتقديم الخدمه الجيدة لهم ولن يكون هوتيلز ايجبت ملتزم او مسئول عن اى خدمه سيئه او غير مقبوله للعميل او لا تلبى توقعاته بأى طريقة.</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:'Times New Roman', serif;">يلتزم الطرف الثانى بأن تكون الاسعار المتواجدة على التطبيق مطابقة لاسعار الحجز المعلنه لديه.</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:'Times New Roman', serif;">يلتزم الطرف الثانى بمتابعة الحجوزات داخل التطبيق بشكل يومى دأئم وتوفير الخدمه لهم فى حالة الطلب والرد على العملاء والتواصل معهم بشكل مباشر.</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:'Times New Roman', serif;">يلتزم الطرف الثانى فى حاله عدم توافر الخدمه المعلن عنها داخل التطبيق وعدم القدرة على تنفيذها ان يقوم بتغيرها الى وضع غير نشط داخل التطبيق حتى لا يتسبب اى ضرر الى العملاء</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:7pt;font-family:'Times New Roman', serif;">&nbsp;</span><span style="font-size:12pt;font-family:'Times New Roman', serif;">يحق لمقدم الخدمة التحفظ على قيمة العمليات المشكوك في صحتها والواردة من مؤسستي فيزا وماستر كارد لحين التأكد من صحة هذه العمليات من عدمه</span><span style="font-size:12pt;font-family:'Times New Roman', serif;">.</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:7pt;font-family:'Times New Roman', serif;">&nbsp;</span><span style="font-size:12pt;font-family:'Times New Roman', serif;">يقبل الطرف الثانى (الشريك ) خصم أية مبالغ يعترض عليها البنك المصدر للبطاقة في حالة عدم قبوله للمستندات المقدمة من الطرف الاول (مقدمة الخدمه ) في حاله عدم ثبوت تقديم الخدمة للعميل</span><span style="font-size:12pt;font-family:'Times New Roman', serif;">.</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:7pt;font-family:'Times New Roman', serif;">&nbsp;</span><span style="font-size:12pt;font-family:'Times New Roman', serif;">يوافق الطرف الثانى (الشريك)على خصم أية مبالغ ترد بها شكوى&nbsp;</span><span style="font-size:12pt;font-family:'Times New Roman', serif;">(</span><span style="font-size:12pt;font-family:'Times New Roman', serif;">اعتراض</span><span style="font-size:12pt;font-family:'Times New Roman', serif;">)&nbsp;</span><span style="font-size:12pt;font-family:'Times New Roman', serif;">من حامل البطاقة المستخدمة في العمليات المنفذة من حسـابه لدى مقدم الخدمة وأضافه القيمة إلى حساب صاحب البطـاقـة المعتـرض وذلك بعد تأكد الطرفين من صحة المبالغ المعترض عليهاوانه هو المسئول امام البنك عن هذه العمليات</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:7pt;font-family:'Times New Roman', serif;">&nbsp;</span><span style="font-size:12pt;font-family:'Times New Roman', serif;">يحق لمقدم الخدمة (الطرف الاول) إيقاف الخدمة فوراً عن الطرف الثانى (الشريك ) في اي وقت ودون سابق إنذار&nbsp;</span><span style="font-size:12pt;font-family:'Times New Roman', serif;">(</span><span style="font-size:12pt;font-family:'Times New Roman', serif;">بصفة مؤقتة&nbsp;</span><span style="font-size:12pt;font-family:'Times New Roman', serif;">/&nbsp;</span><span style="font-size:12pt;font-family:'Times New Roman', serif;">بصفة نهائية</span><span style="font-size:12pt;font-family:'Times New Roman', serif;">)&nbsp;</span><span style="font-size:12pt;font-family:'Times New Roman', serif;">في حالة زيادة نسبة العمليات المشكوك في صحتها وفقاً للتقارير الواردة لمقدم الخدمة من مؤسستي فيزا وماستر كارد في هذا الخصوص أو لأي سبب أخر يري معه الطرف الأول هذا الاجراء حماية لجميع الاطراف من مخاطر محتمله وذلك حفاظا على حقوق جميع الأطراف مع ضرورة إخطار الطرف الثاني (الشريك )&nbsp;<a></a>بهذا الاجراء</span><span style="font-size:12pt;font-family:'Times New Roman', serif;">.</span></li>
                    </ol>
                    <p class="MsoNormal" style="text-align:right;"><strong><span style="font-family:Arial, 'sans-serif';">البند الرابع - النسبة :</span></strong></p>
                    <ol>
                        <li class="MsoNormal" style="text-align:right;"><strong><span style="font-size:14pt;font-family:Arial, 'sans-serif';">&nbsp;</span></strong><span style="font-size:12pt;font-family:Arial, 'sans-serif';">اتفق الطرفان على ان يقوم الطرف الثانى بدفع نسبة {10%} من اجمالى المبيعات المحققه والمسجلة فى حساب الطرف الثانى عن طريق تطبيق هوتيلز ايجبت.</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:Arial, 'sans-serif';">اتفق الطرفان على ان يقوم الطرف الاول بأيداع صافى الحجوزات مخصوما منها النسبه المذكوره اعلاه للطرف الثانى فى حسابه البنكى رقم{المسجل داخل الموقع }.</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:Arial, 'sans-serif';">اتفق الطرفان على ان يقوم الطرف الاول بتحول صافى الايرادات بعد خصم النسبه المذكوره اعلاه ثلاث مرات اسبوعيا.</span></li>
                    </ol>
                    <p class="MsoNormal" style="text-align:right;"><strong><span style="font-family:Arial, 'sans-serif';">البند الخامس - احكام عامة :</span></strong></p>
                    <ul>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:Arial, 'sans-serif';">أى مراسلات يتم ارسالها للطرف الثانى (الشريك)تصبح ملزمه ومكملة للاتفاقية سواء كان ذلك عن طريق ارسالها بالبريد العادى او الالكترونى .</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:Arial, 'sans-serif';">يقر الطرف الثانى (الشريك)بأن جميع المراسلات المستلمة من قبل المؤسسات العالمية او البنوك الخارجيه لها حجتها ولا يجوز الطعن عليها او التشكيك بصحتها.</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:Arial, 'sans-serif';">يتعين على الطرف الثانى تحديد واظهار سياسة الاسترجاع والاستبدال للخدمات المؤداه فى صحة شراء العميل على ان يوافق عليها العميل قبل عملية الدفع الالكترونى.</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:Arial, 'sans-serif';">لا يتم عمل استرجاع للعمليات التى تمت الا عن طريق منصه فورى باى وعلى نفس طريقة السداد والبطاقة المستخدمه خلال مدة اقصاها (90) يوم من تاريخ العملية مع شرط وجود مبالغ مستحقه للطرف الثانى تغطى مبلغ العمليه المراد إستراداها ولا يسرى ذلك على الاعترضات المتعارف عليها دوليا</span><span style="font-size:14pt;font-family:Arial, 'sans-serif';">.</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:Arial, 'sans-serif';">يقر ويلتزم الطرف الثانى (الشريك)بتقديم كافة البيانات الخاصه بالعميل وبيانات المعاملات وذلك فى حالة وجود اى شكوك بصحة المعامله لدى فورى او البنك الراعى المشارك فى تمرير المعاملات عند قيام العميل باستخدام البطاقات البنكيه او المحافظ الالكترونيه كما يلتزم بتقديم اوجة التعاون فى المعاملات التى تخص مكافحة الاحتيال, تمويل الارهاب, غسيل الاموال وأى معاملات تتم بشكل غير قانونى وذلك حرصا على حماية النشاط والافراد لدى الطرفان.</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:Arial, 'sans-serif';">يلتزم الطرف الثانى (الشريك)باتخاذ جميع الاجراءات اللازمه للتاكد من شخصبة مستخدم بطاقة الدفع الالكترونية بأى وسيله يراها مناسبة ويعد الطرف الثانى مسئول مسئولية كاملة عن ذلك.</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:Arial, 'sans-serif';">يلتزم الطرف الثانى (الشريك)بتقديم الخدمات |المنتجات لحامل البطاقة دون اضافة اى مصروفات او عملات نتيجة استخدام البطاقة الالكترونية وفى حالة عدم الالتزام بذلك يحق للطرف الاول (مقدم الخدمه) خصم الفروق من حساب الطرف الثانى وردها لاصحاب البطاقات المستخدمه وتحمييلة باى غرامات تستحق نتيدة هذا الاخلال وفى حالة التكرار يحق للطرف الاول (مقدم الخدمه ) ايقاف الخدمه بصفه (مؤقته | نهائية ) عن الطرف الثانى .</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:Arial, 'sans-serif';">يلتزم الطرف الثانى (الشريك)بارسال ايصال إلكترونى او البريد الالكترونى لحاملى بطاقة الدفع الالكترونية الذى قام بالسداد يفيد بسدادة القيمه ويعد ذلك بمثابة إقرار ومستند رسمى من الطرف الثانى يفيد حصولة على المبلغ من حامل بطاقة الدفع الالكترونيه ودون أدنى مسئولية على الطرف الاول (مقدم الخدمه ) فى مواجهة الطرف الثانى او حامل البطاقه او بنكه.</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:Arial, 'sans-serif';">حق للطرف الاول (مقدم الخدمه) التحفظ على قيمة العمليات المشكوك فى صحتها والوارده من مؤسستى فيزا وماستر كارد لحين التاكد من صخة هذه العمليات من عدمه.</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:Arial, 'sans-serif';">يقبل الطرف الثانى (الشريك)خصم ايه مبالغ يعترض عليها البنك المصدر للبطاقه فى حالة عدم قبوله للمستندات المقدمه من الطرف الثانى (الشريك)فى حالة عدم ثبوت تقديم الخدمه للعميل.</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:Arial, 'sans-serif';">يوافق الطرف الثانى (الشريك)على خصم ايه مبالغ ترد بها شكوى ( اعتراض ) من حامل البطاقه المستخدمه فى العمليات المنفذه من حسابة لدى الطرف الاول (مقدم الخدمه) ايقاف واضافة القيمه الى حساب صاحب البطاقه المعترض وذلك بعد تاكد الطرفين من صحة المبالغ المعترض عليها</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:Arial, 'sans-serif';">يحق للطرف الاول (مقدم الخدمه) ايقاف الخدمه فورا عن التاجر فى اى وقت ودون سابق انذار (بصفه مؤقته | بصفه نهائية) فى حالة زيادة نسبة العمليات المشكوك فى صحتها وفقا للتقارير&nbsp;الواردة للطرف الاول (مقدم الخدمه) من مؤسستى فيزا وماستر كارد فى هذا الخصوص او لاى سبب اخر يرى معه الطرف الاول هذا الاجراء حمايه لجميع الاطراف من مخاطر محتملة وذلك حفاظا على حقوق جميع الاطراف مع ضرورة إخطار الطرف الثانى بهذا الاجراء.</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:Arial, 'sans-serif';">يلتزم الطرف الثانى (الشريك) بتوضيح السياسه الماليه الخاصه بالخدمات | المنتجات التى يقدمها على الموقع الالكترونى الخاصه به والتطبيقات الالكترونيه من حيث الوصف الكامل والدقيق للمنتجات والخدمات وقيمتها وكيفية ومدة الحصول عليها وشروط عمليات المرتجعات او الالغاءات وتفاصيل عن وسائل الاتصال بما فى ذلك رقم التليفون والعنوان وعنوان البريد الالكترونى والاعلان عن ذلك صراحة بصفة مستمره طوال ايام الاسبوع بما فى ذلك ايام العطلات الاسبوعية والرسميه وعلى مدار 24 ساعه يوميا على موقعه الالكترونى او التطبيقات الالكترونيه لتنفيذ طلبات السداد وفقا للإجراءات الفنيه التى يتفق عليها كتابيا بين الفنيين من الطرفان.</span></li>
                        <li class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:Arial, 'sans-serif';">يوافق ويعتهد الطرف الثانى (الشريك)بأن يتحمل أى تعويضات يطال بها الطرف الاول (مقدم الخدمه) وفقا للقانون نتيجة لأى خسائر لاحقة او كسب فائت نتيجة لاستخدامه البرنامج كما يلتزم بأى مطالبات يطالب بها أى طرف أخر نتيجة لخرقه اى من بنود هذا العقد.</span></li>
                    </ul>
                    <p class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:Arial, 'sans-serif';">&nbsp;</span></p>
                    <p class="MsoNormal" style="text-align:right;"><strong><span style="font-size:14pt;font-family:Arial, 'sans-serif';">البند السادس- التواصـل&nbsp;</span></strong></p>
                    <p class="MsoNormal" style="text-align:right;"><strong><span style="font-size:14pt;font-family:'Times New Roman', serif;">&nbsp;</span></strong><span style="font-size:14pt;font-family:Arial, 'sans-serif';">الايملات الرسمية والارقام لشركة عرابيا :</span></p>
                    <p class="MsoNormal" style="text-align:right;"><span style="font-size:14pt;font-family:'Times New Roman', serif;">0653614742</span><span style="font-family:'Times New Roman', serif;"><span>&nbsp; </span>-<span>&nbsp; </span></span><span style="font-size:14pt;font-family:'Times New Roman', serif;">01004429291</span></p>
                    <p class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:'Times New Roman', serif;"><a href="mailto:info@hoteelsegypt.com"><span style="font-size:14pt;color:#0000FF;">info@hoteelsegypt.com</span></a><span>&nbsp; </span>-<span>&nbsp; </span><a href="mailto:hoteels.egypt@gmail.com"><span style="font-size:14pt;color:#0000FF;">hoteels.egypt@gmail.com</span></a><span>&nbsp; </span>-<span>&nbsp; </span><a href="mailto:arabia.hu@gmail.com"><span style="font-size:14pt;color:#0000FF;">arabia.hu@gmail.com</span></a></span></p>
                    <p class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:'Times New Roman', serif;">&nbsp;</span></p>
                    <p class="MsoNormal" style="text-align:right;"><span style="font-size:14pt;font-family:Arial, 'sans-serif';">الايملات الرسميه والارقام ( الشريك ) : البريد الاليكتروني و رقم الهاتف المذكورين بحساب الشريك الاليكتروني علي موقع هوتيلز ايجيبت ( </span><span style="font-family:Arial, 'sans-serif';">www.hoteelsegypt.com</span><span style="font-size:14pt;font-family:Arial, 'sans-serif';"> )</span></p>
                    <p class="MsoNormal" style="text-align:right;"><strong><span style="font-family:Arial, 'sans-serif';">&nbsp;</span></strong></p>
                    <p class="MsoNormal" style="text-align:right;"><strong><span style="font-size:14pt;font-family:Arial, 'sans-serif';">البند السابع - القانون واجب التطبيق وتسوية المنازعات :</span></strong></p>
                    <p class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:Arial, 'sans-serif';">يسرى على هذا العقد أحكام البنك المركزى المصرى و المنظمات الدولية ذات الصله وأى جهة رقابية أخرى كما يخضع هذا العقد ويفسر طبقا لأحكام القانون المصرى وتختص محاكم القاهرة بكافة أنواعها ودرجاتها بالفصل فى</span> <span style="font-size:12pt;font-family:Arial, 'sans-serif';">أى نزاع قد ينشأ بين الاطراف بسبب تفسير او تنفيذ اى بند من بنود هذا العقد وذلك فى حالة عدم حلها بالطرق الودي.</span></p>
                    <p class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:'Times New Roman', serif;">&nbsp;</span></p>
                    <p class="MsoNormal" style="text-align:right;"><strong><span style="font-size:14pt;font-family:Arial, 'sans-serif';">البد الثامن - شروط واحكام :</span></strong></p>
                    <p class="MsoNormal" style="text-align:right;"><strong><span style="font-size:12pt;font-family:Arial, 'sans-serif';">&nbsp;</span></strong><span style="font-size:12pt;font-family:Arial, 'sans-serif';">يشكل هذا العقد وملاحقة الاتفاق الكامل بين الاطراف فيما يختص بموضوعه وفى حالة اعتبار الا نص من نصوص هذا العقد لاغيا او باطلا او غير قانونى او غير سارى او غير نافذ المفعول لن يؤثر هذا على نفاذ باقى النصوص، ولا يجوز تعديل هذا العقد إلا بموافقة كتابية&nbsp; من الطرفين ولا يعد أى تنازل عن اى بند من بنود هذا العقد صحيحا وملزما ما لم يكون التنازل كتابيا وموقع من قبل الطرف المتنازل</span><span style="font-size:14pt;font-family:Arial, 'sans-serif';">.</span></p>
                    <p class="MsoNormal" style="text-align:right;"><span style="font-size:14pt;font-family:Arial, 'sans-serif';">&nbsp;</span></p>
                    <p class="MsoNormal" style="text-align:right;"><strong><span style="font-size:14pt;font-family:Arial, 'sans-serif';">البند التاسع - مدة العقد :</span></strong></p>
                    <p class="MsoListParagraphCxSpFirst" style="text-align:right;margin:0in 0.5in 10pt 0in;"><span style="font-size:12pt;font-family:Symbol;"><span>·<span style="font:7pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><span style="font-size:12pt;font-family:Arial, 'sans-serif';">هذا العقد سارى المفعول من تاريخ تحريره ويظل معمولا به وملزم للأطراف لمدة (1) سنه واحده من التاريخ المذكور بصدر العقد ما لم يتفق الأطراف كتابه على الانهاء المبكر للعقد ويجدد هذا العقد تلقائيا لمدد مماثلة إضافية يذات الشروط ما لم يقد احد الاطراف بأختار باقى الاطراف كتابه برغبته فى تعديل أى من البنود او عدم تجديد العقد قبل انقضاء المدة السارية حينئذ بمده شهر على الاقل.</span></p>
                    <p class="MsoListParagraphCxSpLast" style="text-align:right;margin:0in 0.5in 10pt 0in;"><span style="font-size:12pt;font-family:Symbol;"><span>·<span style="font:7pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><span style="font-size:12pt;font-family:Arial, 'sans-serif';">يحق لأى من الاطراف إلغاء العقد مع أخطار باقى الاطراف بعدم رغبته فى استمرار تقديم الخدمات على أن لايؤثر على اى من الحقوق والالتزامات التى نشأت نتيجة لعذا العقد لأى من طرفيه قبل تاريخ الإلغاء ولو استحقت تلك الحقوق او الالتزامات بعد هذا التاريخ.</span></p>
                    <p class="MsoNormal" style="text-align:right;"><span style="font-size:12pt;font-family:'Times New Roman', serif;">&nbsp;</span></p>
                    <p class="MsoNormal" style="text-align:right;"><strong><span style="font-size:12pt;font-family:Arial, 'sans-serif';">حرر هذا العقد الكترونيا وفى حالة الموافقه على الشروط والاحكام المذكوره داخل العقد يلتزم كلا من الطرفين الطرف الاول ( مقدم الخدمه ) والطرف الثانى ( الشريك ) بتنفيذ بنوده وفى حاله لا قدر الله نشوب اى نزاع تختص محاكم القاهرة بكافة أنواعها ودرجاتها بالفصل فى أى نزاع قد ينشأ بين الاطراف بسبب تفصير او عدم تنفيذ اى بند من بنود هذا العقد وذلك فى حالة عدم حلها بالطرق الودي.</span></strong></p>
                    <p>&nbsp;</p>
                    <p>&nbsp;</p>
                </div>
            </div>
        </div>
    </div>
</template>
<script>
import Breadcrumbs from "./Layouts/Breadcrumbs";
export default {
    name: 'BecomeVendorConditions',
    components:{
        Breadcrumbs
    },
    data() {
        return {}
    },
    methods: {}
}
</script>
